#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4

    # 行番号を固定
    relativenumber = 0
    enable_tabline_filetype_icon = true
    #enable_statusline_mode = false

    # filemanagerをnerdtreeに
    filemanager = "nerdtree"
    # filemanagerをnerdtreeに
    filetree_direction = "left"

    vim_help_language = "jp"

    # chekkerの設定
    enable_neomake = false
    enable_ale = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 50

[[layers]]
name = "colorscheme"
[[layers]]
  name = "checkers"
[[layers]]
  name = "debug"
[[layers]]
   name = "denite"
[[layers]]
name = "default"
[[layers]]
  name = "tools"

# languages
[[layers]]
  name = "japanese"
[[layers]]
  name = "lang#html"
[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true
[[layers]]
  name = "lang#typescript"
[[layers]]
  name = "lang#vue"
[[layers]]
  name = "lang#markdown"
